package kr.bodywell.health.model

object Constant {
	const val PREFERENCE = "PREFERENCE"
	const val GOOGLE = "GOOGLE"
	const val NAVER = "NAVER"
	const val KAKAO = "KAKAO"
	const val ADMIN = "ADMIN"
	const val USER = "USER"
	const val DEVICE = "DEVICE"
	const val PROFILES = "profiles"
	const val FILES = "files"
	const val FOODS = "foods"
	const val FOOD_USAGES = "food_usages"
	const val DIETS = "diets"
	const val WATER = "water"
	const val ACTIVITIES = "activities"
	const val ACTIVITY_USAGES = "activity_usages"
	const val WORKOUTS = "workouts"
	const val BODY_MEASUREMENTS = "body_measurements"
	const val SLEEP = "sleep"
	const val MEDICINES = "medicines"
	const val MEDICINE_TIMES = "medicine_times"
	const val MEDICINE_INTAKES = "medicine_intakes"
	const val NOTES = "notes"
	const val GOALS = "goals"
	const val FEMALE = "Female"
	const val MALE = "Male"
	const val BREAKFAST = "BREAKFAST"
	const val LUNCH = "LUNCH"
	const val DINNER = "DINNER"
	const val SNACK = "SNACK"
	const val HIGH = "HIGH"
	const val MODERATE = "MODERATE"
	const val LOW = "LOW"
	const val HAPPY = "Happy"
	const val PEACEFUL = "Peaceful"
	const val EXCITED = "Excited"
	const val SAD = "Sad"
	const val ANGRY = "Angry"
}